### ISSUE TITLE
No fabric version for 1.19.3

### ISSUE THREAD

**Issue by JR1258** [blackd/libIPN#10]
theres an inventory sort mod for 1.19.3 but no libipn for 1.19.3...

**Comment by blackd** [comment]
First please use the proper names for my mods!

1.19.3 is no longer supported by the latest version of both mods

these are the last 1.19.3 versions 

https://legacy.curseforge.com/minecraft/mc-mods/libipn/files/4453752

https://legacy.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4469003
