### ISSUE TITLE
Add Modrinth 1.20.1 version

### ISSUE THREAD

**Issue by SorkoPiko** [blackd/libIPN#12]
Hey, I'm well aware that the current version of libIPN supports 1.20.1, however my mod updater (ferium) doesn't see it as being 1.20.1, and thus causes issues. If you could change the version from 1.20 to 1.20-1.20.1, it would be greatly appreciated. (I use fabric BTW)

**Comment by blackd** [comment]
yaep.... I thought I updated it

**Comment by blackd** [comment]
done
