### ISSUE TITLE
No version compatible with Minecraft 1.20.1

### ISSUE THREAD

**Issue by DarkkRevenant** [blackd/libIPN#15]
There is no version of libIPN 4.0.0 compatible with Minecraft version 1.20.1. This issue is causing people to not be able to run mods like Inventory Profiles Next.

**Comment by blackd** [comment]
curseforge or Modrinth?

**Comment by blackd** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/libipn/files/4713499

https://legacy.curseforge.com/minecraft/mc-mods/libipn/files/4713495


https://modrinth.com/mod/libipn/version/forge-1.20-4.0.0

oh I guess the Modrinth one is not marked as 1.20.1

https://modrinth.com/mod/libipn/version/fabric-1.20-4.0.0
