### ISSUE TITLE
Release on Key doesn't work correctly

### ISSUE THREAD

**Issue by Icey67** [blackd/libIPN#17]
### Have you asked for help on discord?

NO

### Minecraft Version/s

1.20.1

### Modloader

Fabric

### Modloader Version

Fabric Loader **0.14.22**
Fabric API **0.89.0**

### Operating System

Windows

### List of all other installed mods

betterf3 7.0.1
c2me 0.2.0+alpha.11.0
cloth-config 11.1.106
clumps 12.0.0.3
cull-less-leaves 1.3.0
enhancedblockentities 0.9+1.20
entityculling 1.6.2-mc1.20.1
fabric-api 0.89.0+1.20.1
fabric-language-kotlin 1.10.10+kotlin.1.9.10
fabricloader 0.14.22
feather release/201cb601
forgeconfigapiport 8.0.0
highlighter 1.1.6
iceberg 1.1.15
inventoryprofilesnext 1.10.7
iris 1.6.9
java 17
lambdynlights 2.3.2+1.20.1
libipn 4.0.0
lithium 0.11.2
malilib 0.16.2
minecraft 1.20.1
modmenu 7.2.2
noxesium 1.0.3+9b339b0
sodium 0.5.3
sound_physics_remastered 1.20.1-1.2.1
starlight 1.1.2+fabric.dbc156f
tweakeroo 0.17.1
voicechat 1.20.1-2.4.24
xaerominimap 23.8.1
xaeroworldmap 1.34.1
yet_another_config_lib_v3 3.1.1+1.20

## What I want to do
I want to make a hotkey for when I hold Left Shift (or Left Ctrl) " it sets "Disable for Dropped Items" in Auto Refill to true
I expected "Press / Release" in the Advanced Keybinding Settings to do the same behaviour

## What actually happens
It acts like a toggle like it's the same as just "Press" or "Release"

https://github.com/blackd/Inventory-Profiles/assets/60461186/6cd6d726-e721-4d3a-82a3-d38f97dfcd4b

### 1.
Open the Inventory Profiles Next Config 
(either with r+c, own keybind, or Mod List)
### 2.
Open Auto Refill Settings
### 3.
Press the Key for the Keybind
(either Shift, Ctrl, etc.)
### 4.
Configure Advanced Key Binding Settings like so:
![image](https://github.com/blackd/Inventory-Profiles/assets/60461186/556e23f2-ec0c-485b-bb26-b68832d1ac57)

### I have tried to reproduce the problem with only or without "Inventory Profiles Next" and its dependencies installed.

- [ ] I have tested without 'Inventory Profiles Next' and its dependencies
- [X] I have tested with only 'Inventory Profiles Next' and its dependencies and no other mods

**Comment by blackd** [comment]
this is probability invalid
please contact us on discord. the checkbox and the explanation in the beginning of the template are there for a reason.

**Comment by Icey67** [comment]
> this is probability invalid please contact us on discord. the checkbox and the explanation in the beginning of the template are there for a reason.

well problem being, i did join your server and there is atm no way for me to contact with the discord because i am stuck in #rules

**Comment by Icey67** [comment]
good news i am no longer stuck in #rules

**Comment by blackd** [comment]
fixed in 4.0.1
