### ISSUE TITLE
4.0.2 is missing for 1.20.1 + fabric on curseforge

### ISSUE THREAD

**Issue by schultzy51** [blackd/libIPN#19]
4.0.2 is missing for 1.20.1 + fabric on curseforge. I see it for 1.20 and 1.20.2 but 1.20.1 seems to be missing. This feels like a minor labeling issue on the library for curseforge. Thanks in advance. Keep up the great work!

![image](https://github.com/blackd/libIPN/assets/624609/4c872dce-7885-4443-92e4-6b3b39f0e84d)
![image](https://github.com/blackd/libIPN/assets/624609/1cfd874a-6cb6-44a2-a05c-fdb0f1703702)
![image](https://github.com/blackd/libIPN/assets/624609/aa622d3f-a14f-4b27-b812-4ab17f5fb85f)
![image](https://github.com/blackd/libIPN/assets/624609/12ea4e02-33a9-4538-a922-e18f7e8f80bc)

**Comment by blackd** [comment]
yeah the 1.20 version also works on 1.20.1
it's fixed now

**Comment by schultzy51** [comment]
It's available now. Thanks for the quick fix!

**Comment by schultzy51** [comment]
It's available now. Thanks for the quick fix!
