### ISSUE TITLE
Mod controll keys show invalid keys on german keyboard

### ISSUE THREAD

**Issue by ST-DDT** [blackd/libIPN#2]
The German keyboard has `y` and `z` swapped, however the mod shows the keys for the English keyboard layout.

Please show the keys using the currently active keyboard layout.

![US Keyboard](https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/KB_United_States-NoAltGr.svg/2560px-KB_United_States-NoAltGr.svg.png)
![DE Keyboard](https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/KB_Germany.svg/2560px-KB_Germany.svg.png)

**Comment by blackd** [comment]
I understand your frustration. I don't use qwerty keyboard as well. 
However translating these is hard and prone to error and even Minecraft doesn't do a particularly good job it self.

**Comment by ST-DDT** [comment]
Minecraft should already have this for their own controls config, don't they?

**Comment by blackd** [comment]
yes
whatever layout is selected during startup is shown

**Comment by blackd** [comment]
done in a398c4c2a9e3fa6a1e6c9d1dba4dedba0317e7f1
at least it works in 1.19 doesn't work in other versions for me
