### ISSUE TITLE
Hotkeys being activated in chat

### ISSUE THREAD

**Issue by srnyx** [blackd/libIPN#3]
**Example:** If I type `/warp` into chat and my `Profiles.Save the current state as "Saved" Profile` hotkey is set to `r + p`, then it'll `Save the current state as "Saved" Profile` because `warp` contains `rp`. *Only happens if you type it fast though.*

**Comment by blackd** [comment]
forge or fabric?

**Comment by srnyx** [comment]
> forge or fabric?

Fabric
