### ISSUE TITLE
Update 1.0.2 Breaks 1.19.2

### ISSUE THREAD

**Issue by Zelioth** [blackd/libIPN#5]
Minecraft 1.19.2 launching instantly crashes after load in of client. I am not sure if it's due to other mods as a capability issue but the older version of libIPN 1.0.1 Works perfectly. I left all other mods alone, downgraded libIPN and the crash went away. 
[crash-2022-10-14_11.14.34-client.txt](https://github.com/blackd/libIPN/files/9788212/crash-2022-10-14_11.14.34-client.txt)

Minecraft 1.19.2
Forge 43.1.39
Pack Friends United

**Comment by blackd** [comment]
yeah looks like forge only problem I'll have an update soon

**Comment by blackd** [comment]
fixed with new release 1.0.3
There were no changes my guess is somehow the upload got mangled with 1.0.2
already available on modrinth curseforge still processing
